# FEATURE EXTRACTION

In [3]:
import pandas as pd
import numpy as np
import glob
import os
from string import Template
import math
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

L=2000

columns=['A','B','C','D','E','F','G','H']

In [4]:
data = pd.DataFrame() #Creating new data frame with the needed features
data['Mean'] = []
data['Max'] = []
data['Min'] = []
data['Median'] = []
data['Mode'] = []
data['Standard_Deviation'] = []
data['Sample_Variance'] = []
data['Kurtosis'] = []
data['Skewness'] = []
data['Range'] = []
data['Sum'] = []
data['RMS'] = []
data['Axis Id'] = []
data['Condition'] = []

data


Empty DataFrame
Columns: [Mean, Max, Min, Median, Mode, Standard_Deviation, Sample_Variance, Kurtosis, Skewness, Range, Sum, RMS, Axis Id, Condition]
Index: []

In [5]:
def find_rms(df1):
    sum=0
    df2=df1.to_numpy()
    for i in df2:
        sum=sum+pow((i),2)
    sum=sum/(len(df1.index))
    return(pow(sum,0.5))
        

In [6]:
def statistics_b(df1): 
    bmean=df1['B'].mean()
    bmax=df1['B'].max()
    bmin=df1['B'].min()
    bmedian=df1['B'].median()
    bmode1=df1['B'].mode()
    if(bmode1[0]):
        bmode=bmode1[0]
    else:                                #multiple modes can exist so taking the first value
        bmode=float(df1['B'].mode())    
    bstddev=df1['B'].std()
    bsamvar=df1['B'].var()
    bkurt=df1['B'].kurt()
    bskew=df1['B'].skew()
    brange=df1['B'].max() - df1['B'].min()
    bsum=df1['B'].sum()
    baxisid=1 #corresponds to the 'B' column 
    bcondition=0 #needs to be updated based on the file from which the data is extracted
    brms=find_rms(df1['B']) #RMS doubt
    blist=[]
    blist.extend((bmean, bmax, bmin, bmedian, bmode, bstddev, bsamvar, bkurt, bskew, brange, bsum, brms, baxisid))
    return blist

In [7]:
def statistics_d(df1): 
    dmean=df1['D'].mean()
    dmax=df1['D'].max()
    dmin=df1['D'].min()
    dmedian=df1['D'].median()
    dmode1=df1['D'].mode()
    if(dmode1[0]):
        dmode=dmode1[0]
    else:                                #multiple modes can exist so taking the first value
        dmode=float(df1['D'].mode())
    dstddev=df1['D'].std()
    dsamvar=df1['D'].var()
    dkurt=df1['D'].kurt()
    dskew=df1['D'].skew()
    drange=df1['D'].max() - df1['D'].min()
    dsum=df1['D'].sum()
    daxisid=2 #corresponds to the 'D' column 
    dcondition=0 #needs to be updated based on the file from which the data is extracted
    drms=find_rms(df1['D']) #RMS doubt
    dlist=[]
    dlist.extend((dmean, dmax, dmin, dmedian, dmode, dstddev, dsamvar, dkurt, dskew, drange, dsum, drms, daxisid))
    return dlist

In [8]:
def statistics_f(df1): 
    fmean=df1['F'].mean()
    fmax=df1['F'].max()
    fmin=df1['F'].min()
    fmedian=df1['F'].median()
    fmode1=df1['F'].mode()
    if(fmode1[0]):
        fmode=fmode1[0]
    else:                                #multiple modes can exist so taking the first value
        fmode=float(df1['F'].mode())
    fstddev=df1['F'].std()
    fsamvar=df1['F'].var()
    fkurt=df1['F'].kurt()
    fskew=df1['F'].skew()
    frange=df1['F'].max() - df1['F'].min()
    fsum=df1['F'].sum()
    faxisid=3 #corresponds to the 'F' column 
    fcondition=0 #needs to be updated based on the file from which the data is extracted
    frms=find_rms(df1['F']) #RMS doubt
    flist=[]
    flist.extend((fmean, fmax, fmin, fmedian, fmode, fstddev, fsamvar, fkurt, fskew, frange, fsum, frms, faxisid))
    return flist

In [9]:
def statistics_h(df1): 
    hmean=df1['H'].mean()
    hmax=df1['H'].max()
    hmin=df1['H'].min()
    hmedian=df1['H'].median()
    hmode1=df1['H'].mode()
    if(hmode1[0]):
        hmode=hmode1[0]
    else:                                #multiple modes can exist so taking the first value
        hmode=float(df1['H'].mode())
    hstddev=df1['H'].std()
    hsamvar=df1['H'].var()
    hkurt=df1['H'].kurt()
    hskew=df1['H'].skew()
    hrange=df1['H'].max() - df1['H'].min()
    hsum=df1['H'].sum()
    haxisid=4 #corresponds to the 'H' column 
    hcondition=0 #needs to be updated based on the file from which the data is extracted
    hrms=find_rms(df1['H']) #RMS doubt
    hlist=[]
    hlist.extend((hmean, hmax, hmin, hmedian, hmode, hstddev, hsamvar, hkurt, hskew, hrange, hsum, hrms, haxisid))
    return hlist

In [10]:
def get_statistics_for_a_file(file_name1,file_number):
    df = pd.read_csv (file_name1,header = None, names = columns)
    df=df.drop(['A','C','E','G'], axis=1) #dropping time-series columns
    rows_count= len(df.index)
    print(rows_count)
    upper_limit=int(rows_count/96000)
    print(upper_limit) #all the excel files have different number of rows
    condition=file_number-745
    for i in range(0,upper_limit):
        df_trim=df.iloc[(96000*i):96000*(i+1)]
        ls_b=statistics_b(df_trim)
        ls_b.append(condition)
        data.loc[len(data)] = ls_b
        ls_d=statistics_d(df_trim)
        ls_d.append(condition)
        data.loc[len(data)] = ls_d
        ls_f=statistics_f(df_trim)
        ls_f.append(condition)
        data.loc[len(data)] = ls_f
        ls_h=statistics_h(df_trim)
        ls_h.append(condition)
        data.loc[len(data)] = ls_h
    
    df_trim=df.iloc[(96000*upper_limit):] #the no of rows is not an exact multiple of 96000
    ls_b=statistics_b(df_trim)
    ls_b.append(condition)
    data.loc[len(data)] = ls_b
    ls_d=statistics_d(df_trim)
    ls_d.append(condition)
    data.loc[len(data)] = ls_d
    ls_f=statistics_f(df_trim)
    ls_f.append(condition)
    data.loc[len(data)] = ls_f
    ls_h=statistics_h(df_trim)
    ls_h.append(condition)
    data.loc[len(data)] = ls_h   

In [11]:
t = Template('D:\Acads\RUL appended data\RULData-$fileno.csv')
for i in range (745,1092):
    file_name=t.substitute({'fileno' : i})
    print(file_name)
    get_statistics_for_a_file(file_name,i)

D:\Acads\RUL appended data\RULData-745.csv
655360
6
D:\Acads\RUL appended data\RULData-746.csv
655360
6
D:\Acads\RUL appended data\RULData-747.csv
655360
6
D:\Acads\RUL appended data\RULData-748.csv
655360
6
D:\Acads\RUL appended data\RULData-749.csv
655360
6
D:\Acads\RUL appended data\RULData-750.csv
655360
6
D:\Acads\RUL appended data\RULData-751.csv
655360
6
D:\Acads\RUL appended data\RULData-752.csv
655360
6
D:\Acads\RUL appended data\RULData-753.csv
655360
6
D:\Acads\RUL appended data\RULData-754.csv
655360
6
D:\Acads\RUL appended data\RULData-755.csv
655360
6
D:\Acads\RUL appended data\RULData-756.csv
655360
6
D:\Acads\RUL appended data\RULData-757.csv
655360
6
D:\Acads\RUL appended data\RULData-758.csv
655360
6
D:\Acads\RUL appended data\RULData-759.csv
655360
6
D:\Acads\RUL appended data\RULData-760.csv
655360
6
D:\Acads\RUL appended data\RULData-761.csv
655360
6
D:\Acads\RUL appended data\RULData-762.csv
655360
6
D:\Acads\RUL appended data\RULData-763.csv
655360
6
D:\Acads\RUL

In [12]:
data.head()

Mean     Max      Min    Median      Mode  Standard_Deviation  \
0  0.001904  2.3583  -1.9646  0.004336  0.099982            0.224263   
1  0.001891  1.0252  -1.0528  0.002462  0.043559            0.119753   
2  0.002680  6.7900  -9.0513 -0.031842 -1.018600            1.239464   
3  0.004350  7.2764 -10.7840 -0.011666 -0.234810            0.792116   
4  0.001871  2.3908  -2.4779  0.005993  0.070065            0.229111   

   Sample_Variance  Kurtosis  Skewness    Range         Sum       RMS  \
0         0.050294  1.863057 -0.055369   4.3229  182.828632  0.224270   
1         0.014341  1.631772 -0.085990   2.0780  181.523049  0.119768   
2         1.536271  1.154255  0.117537  15.8413  257.252466  1.239461   
3         0.627447  4.681745  0.037352  18.0604  417.575527  0.792123   
4         0.052492  2.120916 -0.091354   4.8687  179.650941  0.229117   

   Axis Id  Condition  
0      1.0        0.0  
1      2.0        0.0  
2      3.0        0.0  
3      4.0        0.0  
4      1.0        0.0

In [13]:
data.tail()


Mean     Max     Min    Median      Mode  Standard_Deviation  \
10071  0.000955  1.3505 -1.3153  0.000478 -0.001721            0.107148   
10072  0.001182  6.1031 -6.5771  0.000974 -0.013204            0.394417   
10073  0.001801  3.7936 -3.0788  0.002557  0.004971            0.173446   
10074  0.007918  1.7106 -1.5091  0.008248  0.006090            0.103669   
10075  0.003750  1.3872 -1.4869  0.003156 -0.020559            0.117411   

       Sample_Variance   Kurtosis  Skewness    Range         Sum       RMS  \
10071         0.011481  10.869827 -0.002720   2.6658   91.719078  0.107152   
10072         0.155565  34.733493 -0.483515  12.6802   93.764484  0.394416   
10073         0.030083  52.595258  1.201224   6.8724  142.954213  0.173454   
10074         0.010747  22.809187 -0.168630   3.2197  628.411561  0.103970   
10075         0.013785  11.463525  0.344873   2.8741  297.593866  0.117470   

       Axis Id  Condition  
10071      4.0      346.0  
10072      1.0      346.0  
10073      2.0      346.0  
10074      3.0      346.0  
10075      4.0      346.0

# Principal Component Analysis (PCA) to construct Health Indicator HI


In [14]:
X = data.drop('Condition', 1)
y = data['Condition']
X

Mean     Max      Min    Median      Mode  Standard_Deviation  \
0      0.001904  2.3583  -1.9646  0.004336  0.099982            0.224263   
1      0.001891  1.0252  -1.0528  0.002462  0.043559            0.119753   
2      0.002680  6.7900  -9.0513 -0.031842 -1.018600            1.239464   
3      0.004350  7.2764 -10.7840 -0.011666 -0.234810            0.792116   
4      0.001871  2.3908  -2.4779  0.005993  0.070065            0.229111   
...         ...     ...      ...       ...       ...                 ...   
10071  0.000955  1.3505  -1.3153  0.000478 -0.001721            0.107148   
10072  0.001182  6.1031  -6.5771  0.000974 -0.013204            0.394417   
10073  0.001801  3.7936  -3.0788  0.002557  0.004971            0.173446   
10074  0.007918  1.7106  -1.5091  0.008248  0.006090            0.103669   
10075  0.003750  1.3872  -1.4869  0.003156 -0.020559            0.117411   

       Sample_Variance   Kurtosis  Skewness    Range         Sum       RMS  \
0             0.050294   1.863057 -0.055369   4.3229  182.828632  0.224270   
1             0.014341   1.631772 -0.085990   2.0780  181.523049  0.119768   
2             1.536271   1.154255  0.117537  15.8413  257.252466  1.239461   
3             0.627447   4.681745  0.037352  18.0604  417.575527  0.792123   
4             0.052492   2.120916 -0.091354   4.8687  179.650941  0.229117   
...                ...        ...       ...      ...         ...       ...   
10071         0.011481  10.869827 -0.002720   2.6658   91.719078  0.107152   
10072         0.155565  34.733493 -0.483515  12.6802   93.764484  0.394416   
10073         0.030083  52.595258  1.201224   6.8724  142.954213  0.173454   
10074         0.010747  22.809187 -0.168630   3.2197  628.411561  0.103970   
10075         0.013785  11.463525  0.344873   2.8741  297.593866  0.117470   

       Axis Id  
0          1.0  
1          2.0  
2          3.0  
3          4.0  
4          1.0  
...        ...  
10071      4.0  
10072      1.0  
10073      2.0  
10074      3.0  
10075      4.0  

[10076 rows x 13 columns]

In [15]:
X_train1  = X.iloc[:3000,:]
X_train2=X.iloc[5016:,:]
X_train=X_train1.append(X_train2)
X_train.reset_index(inplace=True,drop=True)


y_train1  = y.iloc[:3000]
y_train2=y.iloc[5016:]
y_train=y_train1.append(y_train2)
y_train.reset_index(inplace=True,drop=True)


X_test= X.iloc[3000:5016,:]
y_test= y.iloc[3000:5016]
X_train

Mean     Max      Min    Median      Mode  Standard_Deviation  \
0      0.001904  2.3583  -1.9646  0.004336  0.099982            0.224263   
1      0.001891  1.0252  -1.0528  0.002462  0.043559            0.119753   
2      0.002680  6.7900  -9.0513 -0.031842 -1.018600            1.239464   
3      0.004350  7.2764 -10.7840 -0.011666 -0.234810            0.792116   
4      0.001871  2.3908  -2.4779  0.005993  0.070065            0.229111   
...         ...     ...      ...       ...       ...                 ...   
10071  0.000955  1.3505  -1.3153  0.000478 -0.001721            0.107148   
10072  0.001182  6.1031  -6.5771  0.000974 -0.013204            0.394417   
10073  0.001801  3.7936  -3.0788  0.002557  0.004971            0.173446   
10074  0.007918  1.7106  -1.5091  0.008248  0.006090            0.103669   
10075  0.003750  1.3872  -1.4869  0.003156 -0.020559            0.117411   

       Sample_Variance   Kurtosis  Skewness    Range         Sum       RMS  \
0             0.050294   1.863057 -0.055369   4.3229  182.828632  0.224270   
1             0.014341   1.631772 -0.085990   2.0780  181.523049  0.119768   
2             1.536271   1.154255  0.117537  15.8413  257.252466  1.239461   
3             0.627447   4.681745  0.037352  18.0604  417.575527  0.792123   
4             0.052492   2.120916 -0.091354   4.8687  179.650941  0.229117   
...                ...        ...       ...      ...         ...       ...   
10071         0.011481  10.869827 -0.002720   2.6658   91.719078  0.107152   
10072         0.155565  34.733493 -0.483515  12.6802   93.764484  0.394416   
10073         0.030083  52.595258  1.201224   6.8724  142.954213  0.173454   
10074         0.010747  22.809187 -0.168630   3.2197  628.411561  0.103970   
10075         0.013785  11.463525  0.344873   2.8741  297.593866  0.117470   

       Axis Id  
0          1.0  
1          2.0  
2          3.0  
3          4.0  
4          1.0  
...        ...  
10071      4.0  
10072      1.0  
10073      2.0  
10074      3.0  
10075      4.0  

[10076 rows x 13 columns]

In [16]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()   #To normalize Data
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [17]:
y_train_arr=y_train.to_numpy() #While normalizing data, X_train and X_test has been converted to array so, for unformality 
y_test_arr=y_test.to_numpy()
y_train_arr

array([  0.,   0.,   0., ..., 346., 346., 346.])

In [18]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [19]:
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.49108563])

# Similarity Matching


In [20]:
def euclidean_distance( a,b):
    sum=0
    for i in range (0,L):
        sum=sum+(pow((a[i]-b[i]),2))
    return(pow(sum,0.5))

In [21]:
def cosine_distance(a,b):
    sum1=0
    sum2=0
    numerator=0
    for i in range (0,L):
        numerator=numerator+(a[i]*b[i])
        sum1=sum1+(pow(a[i],2))
        sum2=sum2+(pow(b[i],2))
    sum3=pow(sum1,0.5)
    sum4=pow(sum2,0.5)
    denominator=sum3*sum4
    fraction=numerator/denominator
    return((1-fraction))

In [22]:
def inverse(a):
    return(pow(a,-1))

In [23]:
y_pred=np.array([])
y_pred

array([], dtype=float64)

In [24]:
no_of_segments=8060-L+1
distance_array=np.array([])
x_te=X_test[16:2016]
for i in range(0,no_of_segments): 
    lower_limit=i;
    upper_limit=(i+L)
    x_sel=X_train[lower_limit:upper_limit]
    print(i)
    print("x_sel:",x_sel.shape)
    print("x_te:",x_te.shape)
    ed=euclidean_distance(x_te,x_sel)
    cd=cosine_distance(x_te,x_sel)
    distance=inverse(ed)+inverse(cd)
    distance_array=np.append(distance_array,distance)

min_index=np.argmin(distance_array,axis=0)
y_pr=y_train_arr[min_index+L-1]
y_pred=np.append(y_pred,y_pr)

0
x_sel: (2000, 1)
x_te: (2000, 1)
1
x_sel: (2000, 1)
x_te: (2000, 1)
2
x_sel: (2000, 1)
x_te: (2000, 1)
3
x_sel: (2000, 1)
x_te: (2000, 1)
4
x_sel: (2000, 1)
x_te: (2000, 1)
5
x_sel: (2000, 1)
x_te: (2000, 1)
6
x_sel: (2000, 1)
x_te: (2000, 1)
7
x_sel: (2000, 1)
x_te: (2000, 1)
8
x_sel: (2000, 1)
x_te: (2000, 1)
9
x_sel: (2000, 1)
x_te: (2000, 1)
10
x_sel: (2000, 1)
x_te: (2000, 1)
11
x_sel: (2000, 1)
x_te: (2000, 1)
12
x_sel: (2000, 1)
x_te: (2000, 1)
13
x_sel: (2000, 1)
x_te: (2000, 1)
14
x_sel: (2000, 1)
x_te: (2000, 1)
15
x_sel: (2000, 1)
x_te: (2000, 1)
16
x_sel: (2000, 1)
x_te: (2000, 1)
17
x_sel: (2000, 1)
x_te: (2000, 1)
18
x_sel: (2000, 1)
x_te: (2000, 1)
19
x_sel: (2000, 1)
x_te: (2000, 1)
20
x_sel: (2000, 1)
x_te: (2000, 1)
21
x_sel: (2000, 1)
x_te: (2000, 1)
22
x_sel: (2000, 1)
x_te: (2000, 1)
23
x_sel: (2000, 1)
x_te: (2000, 1)
24
x_sel: (2000, 1)
x_te: (2000, 1)
25
x_sel: (2000, 1)
x_te: (2000, 1)
26
x_sel: (2000, 1)
x_te: (2000, 1)
27
x_sel: (2000, 1)
x_te: (2000, 1)
28

<ipython-input-22-7e03e72e6b2f>:2: RuntimeWarning: divide by zero encountered in reciprocal
  return(pow(a,-1))


3024
x_sel: (2000, 1)
x_te: (2000, 1)
3025
x_sel: (2000, 1)
x_te: (2000, 1)
3026
x_sel: (2000, 1)
x_te: (2000, 1)
3027
x_sel: (2000, 1)
x_te: (2000, 1)
3028
x_sel: (2000, 1)
x_te: (2000, 1)
3029
x_sel: (2000, 1)
x_te: (2000, 1)
3030
x_sel: (2000, 1)
x_te: (2000, 1)
3031
x_sel: (2000, 1)
x_te: (2000, 1)
3032
x_sel: (2000, 1)
x_te: (2000, 1)
3033
x_sel: (2000, 1)
x_te: (2000, 1)
3034
x_sel: (2000, 1)
x_te: (2000, 1)
3035
x_sel: (2000, 1)
x_te: (2000, 1)
3036
x_sel: (2000, 1)
x_te: (2000, 1)
3037
x_sel: (2000, 1)
x_te: (2000, 1)
3038
x_sel: (2000, 1)
x_te: (2000, 1)
3039
x_sel: (2000, 1)
x_te: (2000, 1)
3040
x_sel: (2000, 1)
x_te: (2000, 1)
3041
x_sel: (2000, 1)
x_te: (2000, 1)
3042
x_sel: (2000, 1)
x_te: (2000, 1)
3043
x_sel: (2000, 1)
x_te: (2000, 1)
3044
x_sel: (2000, 1)
x_te: (2000, 1)
3045
x_sel: (2000, 1)
x_te: (2000, 1)
3046
x_sel: (2000, 1)
x_te: (2000, 1)
3047
x_sel: (2000, 1)
x_te: (2000, 1)
3048
x_sel: (2000, 1)
x_te: (2000, 1)
3049
x_sel: (2000, 1)
x_te: (2000, 1)
3050
x_sel: 

In [25]:
print(min_index)

2


In [26]:
y_pred.shape

(1,)

In [27]:
y_test_arr.shape

(2016,)

In [28]:
y_test1=np.array([])
y_test1=np.append(y_test1,y_test_arr[2015])
y_test_arr[2010:2015]

array([174., 174., 174., 174., 174.])

In [29]:
y_pred

array([70.])

In [30]:
y_test1

array([174.])

In [31]:
mean_squared_error(y_test1, y_pred)

10816.0

In [32]:
mean_absolute_error(y_test1,y_pred)

104.0